ATB 1192 | Upgrade node version from 18.* to 20.*
govuk-one-login/account-interventions-service pull request #197
Opened 2024-01-29 17:21 UTC by liamquayle

## Proposed changes
[ATB-1192](https://govukverify.atlassian.net/browse/ATB-1192)

### What changed
Updated node versions from 18 to 20

### Why did it change
optimisation

## Testing
Changes seen in AWS:
<img width="1575" alt="Screenshot 2024-01-29 at 15 33 00" src="https://github.com/govuk-one-login/account-interventions-service/assets/130994595/e64c0a16-dd08-4214-af04-8ec01928aacc">

## Checklists
- [x] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [x] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [x] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [ ] Ensured that no log lines include PII or other sensitive data
- [ ] Implemented unit testing for any new logic implemented, if appropriate
- [x] Ensured that all commits in this PR are signed
- [ ] Ensured appropriate code coverage is maintained by unit tests
- [ ] Checked SonarCube and ensured no code smells were added

2024-01-29 18:07 UTC, TaherKapasi commented
Hi @liamquayle - could you update the "@types/node": in the feature test's package.json.

More importantly, we also need to update tsconfig.json in both root and features to transpile code to Node 20.
```
    "lib": ["es2023", "dom"],
    "module": "node16",
    "target": "es2022",
```

2024-01-29 18:21 UTC, TaherKapasi requested changes
Need to do fea

2024-01-31 12:10 UTC, TaherKapasi approved these changes

2024-01-31 12:22 UTC, amd-gds approved these changes

2024-02-01 12:24 UTC, merged