ATB 1485 | Exclude AUTH_PASSWORD_SUCCESSFUL_FOR_TEST_CLIENT codes from allowable_interventions
govuk-one-login/account-interventions-service pull request #204
Opened 2024-02-01 12:08 UTC by amd-gds

## Proposed changes

### What changed
Added all non intervention codes to the constant that's holding them.

### Why did it change
At the moment, only codes for AUTH_PASSWORD_RESET_SUCCESSFUL and IPV_IDENTITY_ISSUED are excluded from the allowable_interventions array that’s being sent in the egress message to TxMA.

We need to exclude the codes for AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT as well.
### Issue tracking

- [ATB-1485](https://govukverify.atlassian.net/browse/ATB-1485)

## Testing
Before:
![image](https://github.com/govuk-one-login/account-interventions-service/assets/124037159/be5a244a-ca18-49d1-919a-e465503fe24c)

After:

## Checklists
- [x] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [x] Tested changes and included test evidence in the PR, if appropriate
- [x] Included all required tags and other properties for any new resources in the SAM template
- [x] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [x] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [x] Ensured that no log lines include PII or other sensitive data
- [x] Implemented unit testing for any new logic implemented, if appropriate
- [x] Ensured that all commits in this PR are signed
- [x] Ensured appropriate code coverage is maintained by unit tests
- [x] Checked SonarCube and ensured no code smells were added

2024-02-01 13:13 UTC, TaherKapasi requested changes

2024-02-01 13:13 UTC, TaherKapasi commented on src/data-types/constants.ts
> +export const nonInterventionsCodes = new Set(['90', '91', '92', '93', '94', '95']);
could we do this dynamically based on edges that do not have an `interventionName`?

2024-02-01 14:23 UTC, liamquayle approved these changes

2024-02-02 09:30 UTC, chiarapascucci-gds approved these changes

2024-02-02 10:53 UTC, BhanusriNarne approved these changes

2024-02-02 12:21 UTC, TaherKapasi approved these changes

2024-02-02 12:25 UTC, merged