ATB-1482: Validate History values does not exceed 2 years
govuk-one-login/account-interventions-service pull request #225
Opened 2024-02-22 18:30 UTC by BhanusriNarne

## Proposed changes

### What changed
Added scenarios to validate history items that exceeds 2 years

### Why did it change
To improve the coverage

### Issue tracking

- [ATB-1482](https://govukverify.atlassian.net/browse/ATB-1482)

## Testing

## Checklists
- [x] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [x] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [ ] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [ ] Ensured that no log lines include PII or other sensitive data
- [ ] Implemented unit testing for any new logic implemented, if appropriate
- [ ] Ensured that all commits in this PR are signed
- [ ] Ensured appropriate code coverage is maintained by unit tests
- [ ] Checked SonarCube and ensured no code smells were added

[ATB-1482]: https://govukverify.atlassian.net/browse/ATB-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-22 18:40 UTC, TaherKapasi requested changes

2024-02-22 18:40 UTC, TaherKapasi commented on feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
> +    and(/^I send an another (.*) and invoke the API$/, async (allowableEventType) => {
```suggestion
    and(/^I send an another (.*) event and then invoke the API$/, async (allowableEventType) => {
```

2024-02-22 18:40 UTC, TaherKapasi commented on feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
> +  test('Happy Path - validate history exceeds 2years - Returns Expected Data for <aisEventType>', ({
```suggestion
  test('Happy Path - validate history does not contain entries older than 2years - Returns Expected Data for <aisEventType>', ({
```

2024-02-22 18:45 UTC, BhanusriNarne commented on feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
> +    and(/^I send an another (.*) and invoke the API$/, async (allowableEventType) => {
updated

2024-02-22 18:45 UTC, BhanusriNarne commented on feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
> +  test('Happy Path - validate history exceeds 2years - Returns Expected Data for <aisEventType>', ({
updated

2024-02-22 19:12 UTC, TaherKapasi approved these changes

2024-02-23 09:47 UTC, amd-gds approved these changes

2024-02-26 10:30 UTC, ChrisBates1 approved these changes

2024-02-26 13:45 UTC, merged