ATB-1068 Added TxMA ingress schema validation
govuk-one-login/account-interventions-service pull request #46
Opened 2023-11-02 13:41 UTC by amd-gds

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [ATB-1068](https://govukverify.atlassian.net/browse/ATB-1068)

## Testing
[Testing-schma-validation.docx](https://github.com/govuk-one-login/account-interventions-service/files/13239429/Testing-schma-validation.docx)

## Checklists
- [ ] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [ ] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [ ] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [ ] Ensured that no log lines include PII or other sensitive data
- [ ] Implemented unit testing for any new logic implemented, if appropriate
- [ ] Ensured that all commits in this PR are signed
- [ ] Ensured appropriate code coverage is maintained by unit tests

2023-11-02 13:54 UTC, TaherKapasi requested changes

2023-11-02 13:54 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +  title: 'Encrypt Event Validator schema',
please update to not reflect VC storage

2023-11-02 13:54 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +          type: 'number',
is there any extended type for timestamps?

2023-11-02 13:54 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +  title: 'Encrypt Event Validator schema',
fraud risk engine intervention event

2023-11-02 13:54 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +export const TxMAIngress = {
could we include the manual fraud interventions and the user led actions txma events as well - thanks

2023-11-02 13:57 UTC, liamquayle commented on src/data-types/schemas.ts
> +          examples: [1234],
small question, we removed the examples field from the schema in vc storage, just to help improve compile time, should we do the same here as a slight optimisation?

2023-11-02 15:05 UTC, jessica-li-01 commented on src/services/validate-event.ts
> +    logger.debug('event has failed schema validation');
Can we change to capital letter and full stop 'Event has failed the schema validation.'?

2023-11-02 15:34 UTC, chiarapascucci-gds commented on src/services/test/validate-event.test.ts
> +      // @ts-ignore
why is ts-ignore needed here?

2023-11-02 15:40 UTC, amd-gds commented on src/services/test/validate-event.test.ts
> +      // @ts-ignore
good spot. it's not!

2023-11-07 16:01 UTC, TaherKapasi approved these changes

2023-11-07 16:39 UTC, TaherKapasi requested changes

2023-11-07 16:39 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +        extension: {
extensions: with an 's' at the end

2023-11-07 16:39 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +  $id: 'https://example.com/object1689242392.json',
give it a better id - use the git url of the schema

2023-11-07 16:39 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +          title: 'Extension',
Extensions

2023-11-07 16:39 UTC, TaherKapasi commented on src/data-types/schemas.ts
> +            email: {
probably should ignore these attributes below as we don't need them and add `additionalProperties: true` just so we don't have to list ones we don't need.

2023-11-10 10:13 UTC, jessica-li-01 commented on src/services/test/validate-event.test.ts
> +  it('should no return anything as event is valid', () => {
*not

2023-11-10 10:13 UTC, jessica-li-01 commented on src/services/test/validate-event.test.ts
> +  it('should return error as intervention is invalid', () => {
*an error

2023-11-10 10:13 UTC, jessica-li-01 commented on src/services/test/validate-event.test.ts
> +  it('should return error as event is invalid', () => {
*an error

2023-11-10 10:13 UTC, jessica-li-01 commented on src/services/test/validate-event.test.ts
> +    expect(logger.debug).toHaveBeenCalledWith('event has failed schema validation');
Can we have a capital letter *Event pls?:)

2023-11-13 08:35 UTC, TaherKapasi approved these changes

2023-11-13 09:15 UTC, chiarapascucci-gds approved these changes

2023-11-13 09:16 UTC, jessica-li-01 approved these changes

2023-11-13 13:11 UTC, merged