ATB-1160 | Set up Integration and Production AWS Account with the dev-platform stacks
govuk-one-login/account-interventions-service pull request #54
Opened 2023-11-07 15:34 UTC by MinaMahdi

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [ATB-XXXX](https://govukverify.atlassian.net/browse/ATB-XXXX)

## Testing

## Checklists
- [ ] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [ ] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [ ] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [ ] Ensured that no log lines include PII or other sensitive data
- [ ] Implemented unit testing for any new logic implemented, if appropriate
- [ ] Ensured that all commits in this PR are signed
- [ ] Ensured appropriate code coverage is maintained by unit tests

2023-11-08 11:16 UTC, TaherKapasi requested changes

2023-11-08 11:16 UTC, TaherKapasi commented on stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json
> +    "ParameterValue": "Yes"
think this can be No

2023-11-08 11:16 UTC, TaherKapasi commented on stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json
> +    "ParameterValue": "Yes"
No

2023-11-08 11:16 UTC, TaherKapasi commented on stack-orchestration/configuration/di-account-interventions-production-admin/vpc/parameters.json
> +[
same as above

2023-11-10 09:32 UTC, TaherKapasi approved these changes

2023-11-10 09:35 UTC, chiarapascucci-gds approved these changes

2023-11-10 10:45 UTC, domantas-gds commented on stack-orchestration/configuration/di-account-interventions-integration-admin/tags.json
> +    "Value": "GOV.UK Sign In"
GOV.UK One Login

2023-11-10 10:45 UTC, domantas-gds commented on stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json
> +    "ParameterValue": "No"
Shall we enable this

2023-11-10 10:49 UTC, domantas-gds commented on stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json
> +    "ParameterValue": "No"
Could we enable please

2023-11-10 10:49 UTC, domantas-gds commented on stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json
> +    "ParameterValue": "No"
For backup as a service EventBridge

2023-11-10 10:50 UTC, domantas-gds commented on stack-orchestration/configuration/di-account-interventions-integration-admin/tags.json
> +    "Value": "GOV.UK Sign In"
For any reference please :)

2023-11-10 10:51 UTC, domantas-gds approved these changes

2023-11-10 12:52 UTC, merged