ATB-1091 | Attained VPC IDs for Orchestration, Authentication and One Login Home
govuk-one-login/account-interventions-service pull request #60
Opened 2023-11-10 11:43 UTC by MinaMahdi

## Proposed changes

ATB 1091: Get VPC IDs or Account IDs for Private API resource policy

### What changed

Updated all Staging VPC ID to vpc-02e4eb3b0cffc08b0 to allow access from di-performance-test-prod (#330163506186*) 
Added Orchestration and Authentication VPC IDs (Shared) in Integration and Production Mappings. 

### Why did it change

To allow our Private ApiGateway to work with Auth, Orch and OLH and to facilitate performance testing in staging. 

### Issue tracking

- [ATB-1091](https://govukverify.atlassian.net/browse/ATB-1091)

## Testing

## Checklists
- [ ] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [ ] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [ ] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [ ] Ensured that no log lines include PII or other sensitive data
- [ ] Implemented unit testing for any new logic implemented, if appropriate
- [ ] Ensured that all commits in this PR are signed
- [ ] Ensured appropriate code coverage is maintained by unit tests

2023-11-10 12:05 UTC, domantas-gds approved these changes

2023-11-10 12:32 UTC, liamquayle approved these changes

2023-11-13 08:41 UTC, TaherKapasi requested changes

2023-11-13 08:41 UTC, TaherKapasi commented on src/infra/main/template.yaml
> +      OrchestrationVPCID: vpc-02e4eb3b0cffc08b0 # Performance testing VPC ID
For staging env, could we add the VPC IDs for Auth and Orch to allow them to test against staging as well as leaving perf in the olh placeholder

2023-11-13 14:53 UTC, domantas-gds approved these changes

2023-11-13 15:14 UTC, TaherKapasi approved these changes

2023-11-13 15:16 UTC, merged