ATB-1190: Ensure status-retriever can handle encoded path parameters
govuk-one-login/account-interventions-service pull request #75
Opened 2023-11-16 12:12 UTC by liamquayle

## Proposed changes
[ATB-1190](https://govukverify.atlassian.net/browse/ATB-1190)

### What changed
Added logic and unit tests to cover the scenario of encoded path parameters along with updating unit tests to cover this.

### Why did it change
Currently the status retriever handler could not handle encoded path parameters, this change is to ensure it can.

## Testing
Locally, via unit tests. Full code coverage:
<img width="731" alt="Screenshot 2023-11-16 at 11 47 50" src="https://github.com/govuk-one-login/account-interventions-service/assets/130994595/01e7cb3b-331c-46ff-af7f-d30eaa9c3ec9">
API Gateway, correctly decodes the user Id and retrieves the record that is matched against it:
<img width="741" alt="Screenshot 2023-11-16 at 12 10 26" src="https://github.com/govuk-one-login/account-interventions-service/assets/130994595/fe989eda-e7e0-4d4a-a321-bc94fc7cb023">

## Checklists
- [x] Did not commit any not-required changes to the `src/infra/**/samconfig.toml`
- [x] Tested changes and included test evidence in the PR, if appropriate
- [ ] Included all required tags and other properties for any new resources in the SAM template
- [ ] Ensured that any new resources in the SAM Template follow appropriate naming conventions
- [ ] Ensured that naming of new resources is compatible with deploying multiple stacks with custom stack names during development
- [x] Ensured that no log lines include PII or other sensitive data
- [x] Implemented unit testing for any new logic implemented, if appropriate
- [x] Ensured that all commits in this PR are signed
- [x] Ensured appropriate code coverage is maintained by unit tests

2023-11-16 13:27 UTC, TaherKapasi requested changes

2023-11-16 13:27 UTC, TaherKapasi commented on src/handlers/tests/status-retriever-handler.test.ts
> +      pk: encodeURIComponent('testUserID'),
```suggestion
pk: encodeURIComponent('test&User?ID'),
```
include chars that will be encoded

2023-11-16 13:27 UTC, TaherKapasi commented on src/handlers/tests/status-retriever-handler.test.ts
> +    mockDynamoDBServiceRetrieveRecords(testEvent.pathParameters ? ['userId'] : encodeURIComponent('testUserID'));
same `test&User?ID`

2023-11-16 14:02 UTC, TaherKapasi requested changes

2023-11-16 14:02 UTC, TaherKapasi commented on src/handlers/tests/status-retriever-handler.test.ts
> +      pk: encodeURIComponent('test&User?ID'),
Hi @liamquayle - apologies the pk should be just `test&User?ID` without being encoded.  Once the lambda decodes the encoded value - it should match the decoded value in the db

2023-11-16 14:11 UTC, TaherKapasi approved these changes

2023-11-20 12:06 UTC, chiarapascucci-gds approved these changes

2023-11-20 12:07 UTC, jessica-li-01 approved these changes

2023-11-20 15:33 UTC, merged